#!/usr/bin/env python3
"""
Self-host all Google Fonts used by MailFlow, with exact parity.

For every css2 query the app uses (font sets in fonts.js + app-chrome links in
index.html), fetch Google's css2 response with a Chrome UA, download each referenced
woff2 into frontend/public/fonts/, and emit a single fonts.css with src rewritten to
same-origin /fonts/... paths.

Dedup rules (important): files are deduped by URL (download once), but @font-face
BLOCKS are deduped by full text — because variable fonts emit several blocks
(different font-weight/style) that share ONE woff2 URL; keying only on URL would
drop weights. Idempotent: existing woff2 files are not re-downloaded.
"""
import re, os, urllib.request

ROOT = "/home/matt/mailflow/frontend"
FONTS_JS = os.path.join(ROOT, "src/fonts.js")
OUT_DIR = os.path.join(ROOT, "public/fonts")
CSS_OUT = os.path.join(OUT_DIR, "fonts.css")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

os.makedirs(OUT_DIR, exist_ok=True)

# 1. Collect every css2 query the app uses: font sets + index.html chrome links
src = open(FONTS_JS, encoding="utf-8").read()
queries = re.findall(r"googleFonts:\s*'([^']+)'", src)
html = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
for href in re.findall(r"fonts\.googleapis\.com/css2\?([^\"']+)", html):
    queries.append(href.replace("&display=swap", "").strip())
queries = list(dict.fromkeys(queries))
print(f"css2 queries (sets + chrome): {len(queries)}")

def http_get(url, text=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data.decode("utf-8") if text else data

files = {}            # woff2_url -> local_rel  (download dedup)
blocks = []           # ordered list of rewritten @font-face block texts
seen_blocks = set()   # dedup identical blocks across queries
subset_counter = {}
gstatic_re = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)")
face_re = re.compile(r"(?:/\*[^*]*\*/\s*)?@font-face\s*\{[^}]*\}", re.S)

for i, q in enumerate(queries, 1):
    url = f"https://fonts.googleapis.com/css2?{q}&display=swap"
    try:
        css = http_get(url, text=True)
    except Exception as e:
        print(f"  [{i}/{len(queries)}] FETCH FAIL: {e}")
        continue
    n = 0
    for m in face_re.finditer(css):
        block = m.group(0)
        um = gstatic_re.search(block)
        if not um:
            continue
        woff_url = um.group(1)
        parts = woff_url.split("/s/")[1].split("/")
        local_rel = f"{parts[0]}/{parts[-1]}"        # <name-seg>/<basename>.woff2
        rewritten = gstatic_re.sub(f"url(/fonts/{local_rel})", block).strip()
        files[woff_url] = local_rel
        if rewritten not in seen_blocks:
            seen_blocks.add(rewritten)
            blocks.append(rewritten)
            lab = re.match(r"/\*\s*([^*]+?)\s*\*/", block)
            if lab:
                s = lab.group(1)
                subset_counter[s] = subset_counter.get(s, 0) + 1
        n += 1
    print(f"  [{i}/{len(queries)}] {q[:46]}... -> {n} faces")

print(f"\nunique woff2 files: {len(files)}   |   unique @font-face blocks: {len(blocks)}")
print("subset breakdown:", subset_counter)

# 2. Download each unique woff2 (idempotent)
downloaded = skipped = failed = total = 0
for woff_url, local_rel in files.items():
    dest = os.path.join(OUT_DIR, local_rel)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        skipped += 1; total += os.path.getsize(dest); continue
    try:
        data = http_get(woff_url)
        open(dest, "wb").write(data)
        downloaded += 1; total += len(data)
        if downloaded % 25 == 0:
            print(f"    downloaded {downloaded} ...")
    except Exception as e:
        print(f"    DL FAIL {woff_url}: {e}"); failed += 1

# 3. Emit combined fonts.css (all distinct blocks)
header = ("/* Self-hosted fonts for MailFlow - generated by scripts, do not hand-edit.\n"
          "   Mirrors Google Fonts css2 output for the exact families/weights/subsets the\n"
          "   app uses, with src rewritten to same-origin /fonts/. No external requests. */\n\n")
with open(CSS_OUT, "w", encoding="utf-8") as f:
    f.write(header)
    f.write("\n".join(blocks) + "\n")

print(f"\n=== DONE ===")
print(f"downloaded: {downloaded}, skipped: {skipped}, failed: {failed}")
print(f"on-disk woff2: {total/1024/1024:.1f} MB / {len(files)} files")
print(f"fonts.css: {os.path.getsize(CSS_OUT)/1024:.0f} KB / {len(blocks)} @font-face blocks")
